apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: admin-cluster
rules:
    - apiGroups: [""]
      resources:
          - namespaces
      verbs:
          - "*"
    - apiGroups: ["*"]
      resources:
          - "*"
      verbs:
          - "*"
