apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: namespace-admin-binding
    namespace: namespace1
subjects:
    - kind: Group
      name: admin-namespace1
      apiGroup: rbac.authorization.k8s.io
    - kind: Group
      name: devops-namespace1
      apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    name: namespace-admin
    apiGroup: rbac.authorization.k8s.io
