apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: secrets-only-binding
    namespace: namespace1
subjects:
    - kind: Group
      name: developers-namespace1
      apiGroup: rbac.authorization.k8s.io
    - kind: Group
      name: qa-namespace1
      apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    name: secrets-only
    apiGroup: rbac.authorization.k8s.io
