apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: view-binding
subjects:
    - kind: Group
      name: developers
      apiGroup: rbac.authorization.k8s.io
    - kind: Group
      name: devops-readonly
      apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: ClusterRole
    name: view
    apiGroup: rbac.authorization.k8s.io
